# Generated by Django 3.1.4 on 2020-12-10 01:16

import datetime
import django.core.validators
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):
    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Posts',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('task', models.CharField(max_length=255, verbose_name='タスク名')),
                ('task_text', models.CharField(max_length=255, verbose_name='タスク詳細')),
                ('created_at',
                 models.DateTimeField(default=datetime.datetime(2020, 12, 10, 1, 16, 20, 994496, tzinfo=utc),
                                      verbose_name='作成日時')),
                ('deadline_at', models.DateTimeField(verbose_name='締切')),
                ('importance', models.IntegerField(validators=[django.core.validators.MinValueValidator(-1),
                                                               django.core.validators.MaxValueValidator(1)])),
                ('Urgency', models.IntegerField(validators=[django.core.validators.MinValueValidator(-1),
                                                            django.core.validators.MaxValueValidator(1)])),
            ],
            options={
                'db_table': 'posts',
            },
        ),
    ]
