# Generated by Django 3.1.4 on 2020-12-10 05:26

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):
    dependencies = [
        ('posts', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='posts',
            name='deadline_at',
        ),
        migrations.AddField(
            model_name='posts',
            name='deadline',
            field=models.DateTimeField(default=datetime.datetime(2020, 12, 13, 5, 26, 50, 742566, tzinfo=utc),
                                       verbose_name='締切'),
        ),
        migrations.AlterField(
            model_name='posts',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2020, 12, 10, 5, 26, 50, 742566, tzinfo=utc),
                                       verbose_name='作成日時'),
        ),
    ]
