# Generated by Django 3.1.4 on 2020-12-15 08:25

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):
    dependencies = [
        ('posts', '0003_auto_20201210_1440'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='posts',
            name='Urgency',
        ),
        migrations.AddField(
            model_name='posts',
            name='urgency',
            field=models.BooleanField(default=True, verbose_name='緊急'),
        ),
        migrations.AlterField(
            model_name='posts',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2020, 12, 15, 8, 25, 2, 501675, tzinfo=utc),
                                       verbose_name='作成日時'),
        ),
        migrations.AlterField(
            model_name='posts',
            name='deadline',
            field=models.DateTimeField(default=datetime.datetime(2020, 12, 15, 8, 25, 2, 501675, tzinfo=utc),
                                       verbose_name='締切'),
        ),
        migrations.AlterField(
            model_name='posts',
            name='importance',
            field=models.BooleanField(default=True, verbose_name='重要'),
        ),
    ]
