# Generated by Django 3.1.4 on 2020-12-15 08:27

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):
    dependencies = [
        ('posts', '0004_auto_20201215_1725'),
    ]

    operations = [
        migrations.AlterField(
            model_name='posts',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2020, 12, 15, 8, 27, 55, 118351, tzinfo=utc),
                                       verbose_name='作成日時'),
        ),
        migrations.AlterField(
            model_name='posts',
            name='deadline',
            field=models.DateTimeField(default=datetime.datetime(2020, 12, 15, 8, 27, 55, 118351, tzinfo=utc),
                                       verbose_name='締切'),
        ),
    ]
